import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: unknown) => jsPDF;
  }
}

export interface ReportData {
  title: string;
  subtitle?: string;
  generatedBy: string;
  generatedAt: Date;
  practiceInfo: {
    name: string;
    address: string;
    phone: string;
    email: string;
  };
}

export interface TableColumn {
  header: string;
  dataKey: string;
  width?: number;
}

export interface TableData {
  columns: TableColumn[];
  rows: Record<string, unknown>[];
}

export interface ChartData {
  title: string;
  data: Array<{ label: string; value: number; color?: string }>;
}

export class PDFReportGenerator {
  private doc: jsPDF;
  private currentY: number = 20;
  private pageHeight: number;
  private pageWidth: number;
  private margin: number = 20;

  constructor() {
    this.doc = new jsPDF();
    this.pageHeight = this.doc.internal.pageSize.height;
    this.pageWidth = this.doc.internal.pageSize.width;
  }

  // Add header with practice info and report title
  addHeader(reportData: ReportData): void {
    const { practiceInfo, title, subtitle, generatedBy, generatedAt } = reportData;

    // Practice logo/name
    this.doc.setFontSize(20);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(practiceInfo.name, this.margin, this.currentY);
    
    this.currentY += 8;
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(practiceInfo.address, this.margin, this.currentY);
    
    this.currentY += 5;
    this.doc.text(`Phone: ${practiceInfo.phone} | Email: ${practiceInfo.email}`, this.margin, this.currentY);

    // Report title
    this.currentY += 15;
    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title, this.margin, this.currentY);

    if (subtitle) {
      this.currentY += 8;
      this.doc.setFontSize(12);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(subtitle, this.margin, this.currentY);
    }

    // Generation info
    this.currentY += 10;
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    this.doc.text(`Generated by: ${generatedBy}`, this.margin, this.currentY);
    this.doc.text(`Generated on: ${generatedAt.toLocaleDateString()} at ${generatedAt.toLocaleTimeString()}`, this.pageWidth - 80, this.currentY);

    // Add separator line
    this.currentY += 5;
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY);
    this.currentY += 10;
  }

  // Add a section title
  addSectionTitle(title: string): void {
    this.checkPageBreak(15);
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(title, this.margin, this.currentY);
    this.currentY += 10;
  }

  // Add paragraph text
  addParagraph(text: string): void {
    this.checkPageBreak(20);
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'normal');
    
    const lines = this.doc.splitTextToSize(text, this.pageWidth - (this.margin * 2));
    this.doc.text(lines, this.margin, this.currentY);
    this.currentY += lines.length * 5 + 5;
  }

  // Add a table
  addTable(tableData: TableData): void {
    this.checkPageBreak(50);
    
    this.doc.autoTable({
      head: [tableData.columns.map(col => col.header)],
      body: tableData.rows.map(row => 
        tableData.columns.map(col => row[col.dataKey] || '')
      ),
      startY: this.currentY,
      margin: { left: this.margin, right: this.margin },
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: 255,
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
      didDrawPage: (data: { cursor: { y: number } }) => {
        this.currentY = data.cursor.y + 10;
      },
    });
  }

  // Add summary statistics
  addSummaryStats(stats: Array<{ label: string; value: string | number; highlight?: boolean }>): void {
    this.checkPageBreak(stats.length * 8 + 20);
    
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text('Summary Statistics', this.margin, this.currentY);
    this.currentY += 10;

    stats.forEach(stat => {
      this.doc.setFontSize(10);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(`${stat.label}:`, this.margin, this.currentY);
      
      if (stat.highlight) {
        this.doc.setFont('helvetica', 'bold');
        this.doc.setTextColor(66, 139, 202);
      }
      
      this.doc.text(String(stat.value), this.margin + 80, this.currentY);
      
      if (stat.highlight) {
        this.doc.setTextColor(0, 0, 0);
        this.doc.setFont('helvetica', 'normal');
      }
      
      this.currentY += 6;
    });
    
    this.currentY += 5;
  }

  // Add a simple bar chart (text-based)
  addSimpleChart(chartData: ChartData): void {
    this.checkPageBreak(chartData.data.length * 8 + 30);
    
    this.doc.setFontSize(12);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(chartData.title, this.margin, this.currentY);
    this.currentY += 10;

    const maxValue = Math.max(...chartData.data.map(d => d.value));
    const barWidth = 100;

    chartData.data.forEach(item => {
      const barLength = (item.value / maxValue) * barWidth;
      
      // Label
      this.doc.setFontSize(9);
      this.doc.setFont('helvetica', 'normal');
      this.doc.text(item.label, this.margin, this.currentY);
      
      // Bar (using rectangles)
      this.doc.setFillColor(item.color || '#428bca');
      this.doc.rect(this.margin + 60, this.currentY - 3, barLength, 4, 'F');
      
      // Value
      this.doc.text(String(item.value), this.margin + 170, this.currentY);
      
      this.currentY += 8;
    });
    
    this.currentY += 10;
  }

  // Add footer
  addFooter(): void {
    const pageCount = this.doc.getNumberOfPages();
    
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(128, 128, 128);
      
      // Page number
      this.doc.text(
        `Page ${i} of ${pageCount}`,
        this.pageWidth - 30,
        this.pageHeight - 10
      );
      
      // Confidentiality notice
      this.doc.text(
        'CONFIDENTIAL - This report contains protected health information',
        this.margin,
        this.pageHeight - 10
      );
    }
  }

  // Check if we need a page break
  private checkPageBreak(requiredSpace: number): void {
    if (this.currentY + requiredSpace > this.pageHeight - 30) {
      this.doc.addPage();
      this.currentY = 20;
    }
  }

  // Generate and download the PDF
  download(filename: string): void {
    this.addFooter();
    this.doc.save(filename);
  }

  // Get PDF as blob for further processing
  getBlob(): Blob {
    this.addFooter();
    return this.doc.output('blob');
  }

  // Get PDF as base64 string
  getBase64(): string {
    this.addFooter();
    return this.doc.output('datauristring');
  }
}
